package io.github.idmit;

/**
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
class Problem2 {
    static int solveFor(int threshold) {
        int twoBack = 1;
        int oneBack = 2;

        int s = 0;

        while (twoBack <= threshold) {
            int fib = oneBack + twoBack;

            if (twoBack % 2 == 0) {
                s += twoBack;
            }

            twoBack = oneBack;
            oneBack = fib;
        }

        return s;
    }
}
